### ISSUE TITLE
Use parameter for the list id

### ISSUE THREAD

**Issue by yfrommelt** [welpdev/mailchimp-bundle#28]
Hello,

The list id is set as a key in config file.
```
welp_mailchimp:
    api_key: "%mailchimp_api_key%"
    lists:
        THELISTID:
```

I would like to set it as a value like this.
```
welp_mailchimp:
    api_key: "%mailchimp_api_key%"
    lists:
        custom_list_name:
             list_id: "%mailchimp_list_id%"
```

Is this fix easy to do ? I have never deal with symfony config development.

**Comment by yfrommelt** [comment]
Oh i can close this issue, I have no idea you can use parameter with a yaml key
```
welp_mailchimp:
    api_key: "%mailchimp_api_key%"
    list_provider: 'welp_mailchimp.list_provider'
    lists:
        "%mailchimp_list_id%":
            subscriber_provider: 'app_mailchimp_subscriber_provider'
```

This config works as excepted.
